language: shell
os: linux
dist: bionic

git:
  depth: false

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8

services:
  - docker

before_install:
  - docker pull ubuntu:focal

script:
  - docker run -it ubuntu:focal apt-get install snapd
  - docker run -it ubuntu:focal snap install snapcraft --classic
  - docker run -it ubuntu:focal snapcraft version