language: shell
os: linux
dist: trusty

git:
  depth: false

env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8

script:
  - wget https://github.com/ymshenyu/travis-test/releases/download/0.0.1/Qv2ray.AppImage
  - chmod +x Qv2ray.AppImage
  - ./Qv2ray.AppImage